trigger: 
  - master

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'app/pom.xml'
              goals: 'package'  # You might need to specify the Maven goals like 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'Cobertura'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
